import { RbListItem } from './rb-list-item';

export const MockRbListItems: RbListItem[] = [
{
  "id": 1,
  "first_name": "Nedi",
  "last_name": "Eckersley",
  "email": "ncaillou0@statcounter.com",
  "gender": "Female",
  "avatar": "https://robohash.org/autvelratione.jpg?size=50x50&set=set1"
}, {
  "id": 2,
  "first_name": "Eadith",
  "last_name": "Drains",
  "email": "esimioli1@cocolog-nifty.com",
  "gender": "Female",
  "avatar": "https://robohash.org/liberoconsequunturqui.bmp?size=50x50&set=set1"
}, {
  "id": 3,
  "first_name": "Leonard",
  "last_name": "Onn",
  "email": "lbothram2@unc.edu",
  "gender": "Male",
  "avatar": "https://robohash.org/necessitatibussaepefuga.jpg?size=50x50&set=set1"
}, {
  "id": 4,
  "first_name": "Cammy",
  "last_name": "Geekin",
  "email": "cpeppin3@irs.gov",
  "gender": "Male",
  "avatar": "https://robohash.org/esteanihil.jpg?size=50x50&set=set1"
}, {
  "id": 5,
  "first_name": "Pet",
  "last_name": "Pues",
  "email": "pspaldin4@slate.com",
  "gender": "Female",
  "avatar": "https://robohash.org/doloremplaceatrepellat.jpg?size=50x50&set=set1"
}, {
  "id": 6,
  "first_name": "Torin",
  "last_name": "Guittet",
  "email": "tbrown5@dedecms.com",
  "gender": "Male",
  "avatar": "https://robohash.org/quidemtemporelabore.bmp?size=50x50&set=set1"
}, {
  "id": 7,
  "first_name": "Art",
  "last_name": "Deal",
  "email": "apalffrey6@apple.com",
  "gender": "Male",
  "avatar": "https://robohash.org/quietvoluptas.bmp?size=50x50&set=set1"
}, {
  "id": 8,
  "first_name": "Murray",
  "last_name": "Credland",
  "email": "mflockhart7@nature.com",
  "gender": "Male",
  "avatar": "https://robohash.org/omnisvitaeet.jpg?size=50x50&set=set1"
}, {
  "id": 9,
  "first_name": "Thebault",
  "last_name": "Screach",
  "email": "tmcturlough8@i2i.jp",
  "gender": "Male",
  "avatar": "https://robohash.org/quasietbeatae.jpg?size=50x50&set=set1"
}, {
  "id": 10,
  "first_name": "Urbain",
  "last_name": "Celler",
  "email": "uchancellor9@liveinternet.ru",
  "gender": "Male",
  "avatar": "https://robohash.org/doloribuspossimusomnis.bmp?size=50x50&set=set1"
}];